# Generated by Django 4.1.9 on 2023-07-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_post_createduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='createduser',
        ),
    ]
