# Generated by Django 4.1.9 on 2023-07-01 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_customuser_groups_customuser_user_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='user',
            new_name='current_user',
        ),
    ]
