# Generated by Django 4.1.9 on 2023-07-01 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_rename_user_connection_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='connected_user',
        ),
    ]
