# Generated by Django 4.1.9 on 2023-07-01 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0011_alter_connection_current_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='current_user',
        ),
    ]
