# Generated by Django 4.1.9 on 2023-07-01 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0012_remove_connection_current_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connectuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='connection',
            name='currentuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usercurrent', to=settings.AUTH_USER_MODEL),
        ),
    ]
